# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fl_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fl_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rfl_grpc.proto\"0\n\x11IdxRequest_uint32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07idx_ori\x18\x02 \x03(\r\"%\n\x12IdxResponse_uint32\x12\x0f\n\x07idx_upd\x18\x01 \x03(\r\"1\n\x11GradRequest_int32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08grad_ori\x18\x02 \x03(\x05\"&\n\x12GradResponse_int32\x12\x10\n\x08grad_upd\x18\x01 \x03(\x05\"1\n\x11GradRequest_float\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08grad_ori\x18\x02 \x03(\x02\"&\n\x12GradResponse_float\x12\x10\n\x08grad_upd\x18\x01 \x03(\x02\"1\n\x11\x44\x61taRequest_int32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x64\x61ta_ori\x18\x02 \x03(\x05\"&\n\x12\x44\x61taResponse_int32\x12\x10\n\x08\x64\x61ta_upd\x18\x01 \x03(\x05\x32\x84\x02\n\x07\x46L_Grpc\x12=\n\x10UpdateIdx_uint32\x12\x12.IdxRequest_uint32\x1a\x13.IdxResponse_uint32\"\x00\x12=\n\x10UpdateGrad_int32\x12\x12.GradRequest_int32\x1a\x13.GradResponse_int32\"\x00\x12=\n\x10UpdateGrad_float\x12\x12.GradRequest_float\x1a\x13.GradResponse_float\"\x00\x12<\n\x0f\x44\x61taTrans_int32\x12\x12.DataRequest_int32\x1a\x13.DataResponse_int32\"\x00\x62\x06proto3'
)




_IDXREQUEST_UINT32 = _descriptor.Descriptor(
  name='IdxRequest_uint32',
  full_name='IdxRequest_uint32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IdxRequest_uint32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idx_ori', full_name='IdxRequest_uint32.idx_ori', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=65,
)


_IDXRESPONSE_UINT32 = _descriptor.Descriptor(
  name='IdxResponse_uint32',
  full_name='IdxResponse_uint32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx_upd', full_name='IdxResponse_uint32.idx_upd', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=104,
)


_GRADREQUEST_INT32 = _descriptor.Descriptor(
  name='GradRequest_int32',
  full_name='GradRequest_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GradRequest_int32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grad_ori', full_name='GradRequest_int32.grad_ori', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=155,
)


_GRADRESPONSE_INT32 = _descriptor.Descriptor(
  name='GradResponse_int32',
  full_name='GradResponse_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_upd', full_name='GradResponse_int32.grad_upd', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=195,
)


_GRADREQUEST_FLOAT = _descriptor.Descriptor(
  name='GradRequest_float',
  full_name='GradRequest_float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GradRequest_float.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grad_ori', full_name='GradRequest_float.grad_ori', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=246,
)


_GRADRESPONSE_FLOAT = _descriptor.Descriptor(
  name='GradResponse_float',
  full_name='GradResponse_float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_upd', full_name='GradResponse_float.grad_upd', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=286,
)


_DATAREQUEST_INT32 = _descriptor.Descriptor(
  name='DataRequest_int32',
  full_name='DataRequest_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DataRequest_int32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_ori', full_name='DataRequest_int32.data_ori', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=337,
)


_DATARESPONSE_INT32 = _descriptor.Descriptor(
  name='DataResponse_int32',
  full_name='DataResponse_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_upd', full_name='DataResponse_int32.data_upd', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=377,
)

DESCRIPTOR.message_types_by_name['IdxRequest_uint32'] = _IDXREQUEST_UINT32
DESCRIPTOR.message_types_by_name['IdxResponse_uint32'] = _IDXRESPONSE_UINT32
DESCRIPTOR.message_types_by_name['GradRequest_int32'] = _GRADREQUEST_INT32
DESCRIPTOR.message_types_by_name['GradResponse_int32'] = _GRADRESPONSE_INT32
DESCRIPTOR.message_types_by_name['GradRequest_float'] = _GRADREQUEST_FLOAT
DESCRIPTOR.message_types_by_name['GradResponse_float'] = _GRADRESPONSE_FLOAT
DESCRIPTOR.message_types_by_name['DataRequest_int32'] = _DATAREQUEST_INT32
DESCRIPTOR.message_types_by_name['DataResponse_int32'] = _DATARESPONSE_INT32
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdxRequest_uint32 = _reflection.GeneratedProtocolMessageType('IdxRequest_uint32', (_message.Message,), {
  'DESCRIPTOR' : _IDXREQUEST_UINT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:IdxRequest_uint32)
  })
_sym_db.RegisterMessage(IdxRequest_uint32)

IdxResponse_uint32 = _reflection.GeneratedProtocolMessageType('IdxResponse_uint32', (_message.Message,), {
  'DESCRIPTOR' : _IDXRESPONSE_UINT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:IdxResponse_uint32)
  })
_sym_db.RegisterMessage(IdxResponse_uint32)

GradRequest_int32 = _reflection.GeneratedProtocolMessageType('GradRequest_int32', (_message.Message,), {
  'DESCRIPTOR' : _GRADREQUEST_INT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradRequest_int32)
  })
_sym_db.RegisterMessage(GradRequest_int32)

GradResponse_int32 = _reflection.GeneratedProtocolMessageType('GradResponse_int32', (_message.Message,), {
  'DESCRIPTOR' : _GRADRESPONSE_INT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradResponse_int32)
  })
_sym_db.RegisterMessage(GradResponse_int32)

GradRequest_float = _reflection.GeneratedProtocolMessageType('GradRequest_float', (_message.Message,), {
  'DESCRIPTOR' : _GRADREQUEST_FLOAT,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradRequest_float)
  })
_sym_db.RegisterMessage(GradRequest_float)

GradResponse_float = _reflection.GeneratedProtocolMessageType('GradResponse_float', (_message.Message,), {
  'DESCRIPTOR' : _GRADRESPONSE_FLOAT,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradResponse_float)
  })
_sym_db.RegisterMessage(GradResponse_float)

DataRequest_int32 = _reflection.GeneratedProtocolMessageType('DataRequest_int32', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST_INT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:DataRequest_int32)
  })
_sym_db.RegisterMessage(DataRequest_int32)

DataResponse_int32 = _reflection.GeneratedProtocolMessageType('DataResponse_int32', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSE_INT32,
  '__module__' : 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:DataResponse_int32)
  })
_sym_db.RegisterMessage(DataResponse_int32)



_FL_GRPC = _descriptor.ServiceDescriptor(
  name='FL_Grpc',
  full_name='FL_Grpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=380,
  serialized_end=640,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateIdx_uint32',
    full_name='FL_Grpc.UpdateIdx_uint32',
    index=0,
    containing_service=None,
    input_type=_IDXREQUEST_UINT32,
    output_type=_IDXRESPONSE_UINT32,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateGrad_int32',
    full_name='FL_Grpc.UpdateGrad_int32',
    index=1,
    containing_service=None,
    input_type=_GRADREQUEST_INT32,
    output_type=_GRADRESPONSE_INT32,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateGrad_float',
    full_name='FL_Grpc.UpdateGrad_float',
    index=2,
    containing_service=None,
    input_type=_GRADREQUEST_FLOAT,
    output_type=_GRADRESPONSE_FLOAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DataTrans_int32',
    full_name='FL_Grpc.DataTrans_int32',
    index=3,
    containing_service=None,
    input_type=_DATAREQUEST_INT32,
    output_type=_DATARESPONSE_INT32,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FL_GRPC)

DESCRIPTOR.services_by_name['FL_Grpc'] = _FL_GRPC

# @@protoc_insertion_point(module_scope)
